### ISSUE TITLE
博主有遇到手机熄屏一段时间 然后打开的时候一直重连 15~30秒左右 但是连接数据线调试的时候又不会出现

### ISSUE THREAD

**Issue by shipan** [liuhaijin/Smack-Openfire#1]

**Comment by shipan** [comment]
org.jivesoftware.smack.SmackException$NotConnectedException: Client is not, or no longer, connected.
                                                   at org.jivesoftware.smackx.ping.PingManager.ping(PingManager.java:164)
                                                   at org.jivesoftware.smackx.ping.PingManager.pingMyServer(PingManager.java:246)
                                                   at org.jivesoftware.smackx.ping.PingManager.pingMyServer(PingManager.java:228)
                                                   at org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary(PingManager.java:370)
                                                   at org.jivesoftware.smackx.ping.PingManager$4.run(PingManager.java:397)
                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                   at java.lang.Thread.run(Thread.java:784)
